version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - 8880:8080
      - 50000:50000
    volumes:
      - /home/panda/jenkins:/var/jenkins_home
    networks:
      - docker-network    

  ubuntu:
    #image: ubuntu:18.04
    build: ./jenkins-ubuntu
    networks:
      - docker-network
    depends_on: 
      - jenkins

networks:
  docker-network:
    driver: bridge