version: '3.9'

services:
  postgres:
    image: postgres
    environment:
    - POSTGRES_PASSWORD=${TMP_PASS}
    - region=${REGION}
  redis:
    image: redis
    environment:
    - region=${REGION}
    