version: '3.9'
#By default docker-compose create network -> <project_name>_default
#file located in folder "compose" means compose_default
services:
  #DNS name = nginx
  nginx:
    image: nginx
    deploy:
      replicas: 2
  #DNS name = custom_ubuntu
  custom_ubuntu:
    build: ./custom_ubuntu